version: "3"
services:
  meetings:
    build: .
    entrypoint: ./cmd/meetings/meetings
  users:
    build: .
    entrypoint: ./cmd/users/users
  api:
    build: .
    command: ./cmd/api/api
    ports:
      - 8080:8080
    links:
      - meetings
      - users
