// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

/*
Package booking_calendar is a generated protocol buffer package.

It is generated from these files:
	users.proto

It has these top-level messages:
	User
	GetUserRequest
	ListUsersRequest
	ListUsersResponse
	CreateUserRequest
	UpdateUserRequest
	DeleteUserRequest
*/
package booking_calendar

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Phone string `protobuf:"bytes,3,opt,name=phone" json:"phone,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GetUserRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ListUsersRequest struct {
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *ListUsersRequest) Reset()                    { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()               {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListUsersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListUsersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListUsersResponse struct {
	Users         []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
	NextPageToken string  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListUsersResponse) Reset()                    { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()               {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type CreateUserRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User       *User                       `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	UpdateMask *google_protobuf1.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *google_protobuf1.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteUserRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "booking_calendar.User")
	proto.RegisterType((*GetUserRequest)(nil), "booking_calendar.GetUserRequest")
	proto.RegisterType((*ListUsersRequest)(nil), "booking_calendar.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "booking_calendar.ListUsersResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "booking_calendar.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "booking_calendar.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "booking_calendar.DeleteUserRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UsersService service

type UsersServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/booking_calendar.UsersService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := grpc.Invoke(ctx, "/booking_calendar.UsersService/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/booking_calendar.UsersService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/booking_calendar.UsersService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/booking_calendar.UsersService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UsersService service

type UsersServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*User, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*google_protobuf.Empty, error)
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.UsersService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.UsersService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.UsersService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.UsersService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.UsersService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "booking_calendar.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UsersService_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UsersService_ListUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UsersService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UsersService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UsersService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}

func init() { proto.RegisterFile("users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xc7, 0x13, 0x92, 0x00, 0x19, 0xf3, 0xa8, 0x57, 0xa8, 0xb2, 0x5c, 0x21, 0x59, 0x8b, 0x54,
	0x15, 0x84, 0x5c, 0x29, 0x1c, 0x39, 0x70, 0x80, 0x96, 0x43, 0x01, 0x21, 0x97, 0x72, 0xb5, 0x36,
	0xcd, 0xd4, 0xac, 0xfc, 0x58, 0xe3, 0xb5, 0x11, 0x54, 0x7c, 0x0c, 0x3e, 0x30, 0xda, 0xd9, 0xbc,
	0xed, 0xe4, 0xd0, 0x9b, 0x3d, 0xfb, 0xcb, 0x7f, 0x66, 0xe7, 0x17, 0x83, 0xd3, 0x68, 0xac, 0x74,
	0x58, 0x56, 0xaa, 0x56, 0xec, 0x60, 0xaa, 0x54, 0x2a, 0x8b, 0x24, 0xbe, 0x16, 0x19, 0x16, 0x33,
	0x51, 0xf9, 0x47, 0x89, 0x52, 0x49, 0x86, 0xa7, 0x74, 0x3e, 0x6d, 0x6e, 0x4e, 0x31, 0x2f, 0xeb,
	0x3f, 0x16, 0xf7, 0x83, 0xed, 0xc3, 0x1b, 0x89, 0xd9, 0x2c, 0xce, 0x85, 0x4e, 0x2d, 0xc1, 0xcf,
	0x61, 0x78, 0xa5, 0xb1, 0x62, 0xcf, 0x60, 0x84, 0xb9, 0x90, 0x99, 0xd7, 0x0f, 0xfa, 0x27, 0xe3,
	0xc8, 0xbe, 0x30, 0x06, 0xc3, 0x42, 0xe4, 0xe8, 0xdd, 0xa3, 0x22, 0x3d, 0x1b, 0xb2, 0xfc, 0xa1,
	0x0a, 0xf4, 0x06, 0x96, 0xa4, 0x17, 0x7e, 0x0c, 0x4f, 0x3e, 0x62, 0x6d, 0xa2, 0x22, 0xfc, 0xd9,
	0xa0, 0xae, 0xbb, 0x13, 0xf9, 0x17, 0x38, 0xf8, 0x24, 0x35, 0x81, 0x7a, 0x41, 0x1e, 0xc1, 0xb8,
	0x14, 0x09, 0xc6, 0x5a, 0xde, 0x22, 0xd1, 0xa3, 0xe8, 0xa1, 0x29, 0x5c, 0xca, 0x5b, 0x64, 0xcf,
	0x01, 0xe8, 0xb0, 0x56, 0x29, 0x16, 0xf3, 0x41, 0x08, 0xff, 0x66, 0x0a, 0x5c, 0x82, 0xbb, 0x96,
	0xa7, 0x4b, 0x55, 0x68, 0x64, 0xaf, 0x61, 0x44, 0x4b, 0xf3, 0xfa, 0xc1, 0xe0, 0xc4, 0x99, 0x1c,
	0x86, 0xdb, 0x5b, 0x0b, 0x69, 0x50, 0x0b, 0xb1, 0x63, 0x78, 0x5a, 0xe0, 0xef, 0x3a, 0x6e, 0xb5,
	0x79, 0x6c, 0xca, 0x5f, 0x97, 0xad, 0xde, 0x81, 0xfb, 0xbe, 0x42, 0x51, 0xe3, 0xfa, 0x2d, 0x5f,
	0xc1, 0xd0, 0xa4, 0xd0, 0xd8, 0xbb, 0x3b, 0x11, 0xc3, 0xff, 0x82, 0x7b, 0x55, 0xce, 0xee, 0x1e,
	0xc0, 0xde, 0x82, 0xd3, 0x50, 0x00, 0x19, 0xa4, 0x29, 0x9d, 0x89, 0x1f, 0x5a, 0xc9, 0xe1, 0x42,
	0x72, 0x78, 0x6e, 0x24, 0x7f, 0x16, 0x3a, 0x8d, 0xc0, 0xe2, 0xe6, 0x99, 0xbf, 0x04, 0xf7, 0x03,
	0x66, 0xb8, 0xd9, 0xbd, 0x53, 0xd2, 0xe4, 0xdf, 0x00, 0x1e, 0xd1, 0x46, 0x2f, 0xb1, 0xfa, 0x25,
	0xaf, 0x91, 0x9d, 0xc1, 0x83, 0xb9, 0x5d, 0x16, 0xb4, 0x27, 0xdc, 0x14, 0xef, 0xef, 0xb8, 0x03,
	0xef, 0xb1, 0xef, 0x30, 0x5e, 0xca, 0x62, 0xbc, 0x8d, 0x6d, 0xff, 0x33, 0xfc, 0x17, 0x7b, 0x19,
	0x6b, 0x9b, 0xf7, 0xd8, 0x05, 0xc0, 0xca, 0x0c, 0xeb, 0xf8, 0x51, 0xcb, 0xdb, 0x9e, 0x21, 0x2f,
	0x00, 0x56, 0x96, 0xba, 0xc2, 0x5a, 0x0e, 0xf7, 0x87, 0xad, 0x96, 0xde, 0x15, 0xd6, 0x52, 0xe2,
	0x1f, 0xb6, 0x7c, 0x9e, 0x99, 0x2f, 0x9a, 0xf7, 0xa6, 0xf7, 0xa9, 0xf2, 0xe6, 0x7f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xe3, 0x43, 0x3e, 0x17, 0x12, 0x04, 0x00, 0x00,
}
