// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/meetings/meetings.proto

/*
Package meetings is a generated protocol buffer package.

It is generated from these files:
	pb/meetings/meetings.proto

It has these top-level messages:
	Time
	Meeting
	GetMeetingRequest
	ListMeetingsRequest
	ListMeetingsResponse
	CreateMeetingRequest
	UpdateMeetingRequest
	DeleteMeetingRequest
*/
package meetings

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "google.golang.org/genproto/protobuf/field_mask"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Time struct {
	DateTime string `protobuf:"bytes,1,opt,name=date_time,json=dateTime" json:"date_time,omitempty"`
	TimeZone string `protobuf:"bytes,2,opt,name=time_zone,json=timeZone" json:"time_zone,omitempty"`
}

func (m *Time) Reset()                    { *m = Time{} }
func (m *Time) String() string            { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()               {}
func (*Time) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Time) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *Time) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

type Meeting struct {
	Parent      string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Start       *Time  `protobuf:"bytes,3,opt,name=start" json:"start,omitempty"`
	End         *Time  `protobuf:"bytes,4,opt,name=end" json:"end,omitempty"`
	Title       string `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Location    string `protobuf:"bytes,7,opt,name=location" json:"location,omitempty"`
}

func (m *Meeting) Reset()                    { *m = Meeting{} }
func (m *Meeting) String() string            { return proto.CompactTextString(m) }
func (*Meeting) ProtoMessage()               {}
func (*Meeting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Meeting) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Meeting) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Meeting) GetStart() *Time {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Meeting) GetEnd() *Time {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Meeting) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Meeting) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Meeting) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type GetMeetingRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetMeetingRequest) Reset()                    { *m = GetMeetingRequest{} }
func (m *GetMeetingRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMeetingRequest) ProtoMessage()               {}
func (*GetMeetingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetMeetingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListMeetingsRequest struct {
	Parent    string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	PageSize  int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *ListMeetingsRequest) Reset()                    { *m = ListMeetingsRequest{} }
func (m *ListMeetingsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListMeetingsRequest) ProtoMessage()               {}
func (*ListMeetingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListMeetingsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListMeetingsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListMeetingsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListMeetingsResponse struct {
	Meetings      []*Meeting `protobuf:"bytes,1,rep,name=meetings" json:"meetings,omitempty"`
	NextPageToken string     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListMeetingsResponse) Reset()                    { *m = ListMeetingsResponse{} }
func (m *ListMeetingsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListMeetingsResponse) ProtoMessage()               {}
func (*ListMeetingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListMeetingsResponse) GetMeetings() []*Meeting {
	if m != nil {
		return m.Meetings
	}
	return nil
}

func (m *ListMeetingsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type CreateMeetingRequest struct {
	Parent  string   `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	Meeting *Meeting `protobuf:"bytes,2,opt,name=meeting" json:"meeting,omitempty"`
}

func (m *CreateMeetingRequest) Reset()                    { *m = CreateMeetingRequest{} }
func (m *CreateMeetingRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateMeetingRequest) ProtoMessage()               {}
func (*CreateMeetingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateMeetingRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateMeetingRequest) GetMeeting() *Meeting {
	if m != nil {
		return m.Meeting
	}
	return nil
}

type UpdateMeetingRequest struct {
	Meeting    *Meeting                    `protobuf:"bytes,1,opt,name=meeting" json:"meeting,omitempty"`
	UpdateMask *google_protobuf1.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *UpdateMeetingRequest) Reset()                    { *m = UpdateMeetingRequest{} }
func (m *UpdateMeetingRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMeetingRequest) ProtoMessage()               {}
func (*UpdateMeetingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateMeetingRequest) GetMeeting() *Meeting {
	if m != nil {
		return m.Meeting
	}
	return nil
}

func (m *UpdateMeetingRequest) GetUpdateMask() *google_protobuf1.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteMeetingRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteMeetingRequest) Reset()                    { *m = DeleteMeetingRequest{} }
func (m *DeleteMeetingRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteMeetingRequest) ProtoMessage()               {}
func (*DeleteMeetingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteMeetingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Time)(nil), "booking_calendar.meetings.Time")
	proto.RegisterType((*Meeting)(nil), "booking_calendar.meetings.Meeting")
	proto.RegisterType((*GetMeetingRequest)(nil), "booking_calendar.meetings.GetMeetingRequest")
	proto.RegisterType((*ListMeetingsRequest)(nil), "booking_calendar.meetings.ListMeetingsRequest")
	proto.RegisterType((*ListMeetingsResponse)(nil), "booking_calendar.meetings.ListMeetingsResponse")
	proto.RegisterType((*CreateMeetingRequest)(nil), "booking_calendar.meetings.CreateMeetingRequest")
	proto.RegisterType((*UpdateMeetingRequest)(nil), "booking_calendar.meetings.UpdateMeetingRequest")
	proto.RegisterType((*DeleteMeetingRequest)(nil), "booking_calendar.meetings.DeleteMeetingRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Meetings service

type MeetingsClient interface {
	GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...grpc.CallOption) (*Meeting, error)
	ListMeetings(ctx context.Context, in *ListMeetingsRequest, opts ...grpc.CallOption) (*ListMeetingsResponse, error)
	CreateMeeting(ctx context.Context, in *CreateMeetingRequest, opts ...grpc.CallOption) (*Meeting, error)
	UpdateMeeting(ctx context.Context, in *UpdateMeetingRequest, opts ...grpc.CallOption) (*Meeting, error)
	DeleteMeeting(ctx context.Context, in *DeleteMeetingRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type meetingsClient struct {
	cc *grpc.ClientConn
}

func NewMeetingsClient(cc *grpc.ClientConn) MeetingsClient {
	return &meetingsClient{cc}
}

func (c *meetingsClient) GetMeeting(ctx context.Context, in *GetMeetingRequest, opts ...grpc.CallOption) (*Meeting, error) {
	out := new(Meeting)
	err := grpc.Invoke(ctx, "/booking_calendar.meetings.Meetings/GetMeeting", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingsClient) ListMeetings(ctx context.Context, in *ListMeetingsRequest, opts ...grpc.CallOption) (*ListMeetingsResponse, error) {
	out := new(ListMeetingsResponse)
	err := grpc.Invoke(ctx, "/booking_calendar.meetings.Meetings/ListMeetings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingsClient) CreateMeeting(ctx context.Context, in *CreateMeetingRequest, opts ...grpc.CallOption) (*Meeting, error) {
	out := new(Meeting)
	err := grpc.Invoke(ctx, "/booking_calendar.meetings.Meetings/CreateMeeting", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingsClient) UpdateMeeting(ctx context.Context, in *UpdateMeetingRequest, opts ...grpc.CallOption) (*Meeting, error) {
	out := new(Meeting)
	err := grpc.Invoke(ctx, "/booking_calendar.meetings.Meetings/UpdateMeeting", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meetingsClient) DeleteMeeting(ctx context.Context, in *DeleteMeetingRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/booking_calendar.meetings.Meetings/DeleteMeeting", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Meetings service

type MeetingsServer interface {
	GetMeeting(context.Context, *GetMeetingRequest) (*Meeting, error)
	ListMeetings(context.Context, *ListMeetingsRequest) (*ListMeetingsResponse, error)
	CreateMeeting(context.Context, *CreateMeetingRequest) (*Meeting, error)
	UpdateMeeting(context.Context, *UpdateMeetingRequest) (*Meeting, error)
	DeleteMeeting(context.Context, *DeleteMeetingRequest) (*google_protobuf.Empty, error)
}

func RegisterMeetingsServer(s *grpc.Server, srv MeetingsServer) {
	s.RegisterService(&_Meetings_serviceDesc, srv)
}

func _Meetings_GetMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingsServer).GetMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.meetings.Meetings/GetMeeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingsServer).GetMeeting(ctx, req.(*GetMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meetings_ListMeetings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeetingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingsServer).ListMeetings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.meetings.Meetings/ListMeetings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingsServer).ListMeetings(ctx, req.(*ListMeetingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meetings_CreateMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingsServer).CreateMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.meetings.Meetings/CreateMeeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingsServer).CreateMeeting(ctx, req.(*CreateMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meetings_UpdateMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingsServer).UpdateMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.meetings.Meetings/UpdateMeeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingsServer).UpdateMeeting(ctx, req.(*UpdateMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Meetings_DeleteMeeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMeetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingsServer).DeleteMeeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking_calendar.meetings.Meetings/DeleteMeeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingsServer).DeleteMeeting(ctx, req.(*DeleteMeetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Meetings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "booking_calendar.meetings.Meetings",
	HandlerType: (*MeetingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMeeting",
			Handler:    _Meetings_GetMeeting_Handler,
		},
		{
			MethodName: "ListMeetings",
			Handler:    _Meetings_ListMeetings_Handler,
		},
		{
			MethodName: "CreateMeeting",
			Handler:    _Meetings_CreateMeeting_Handler,
		},
		{
			MethodName: "UpdateMeeting",
			Handler:    _Meetings_UpdateMeeting_Handler,
		},
		{
			MethodName: "DeleteMeeting",
			Handler:    _Meetings_DeleteMeeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/meetings/meetings.proto",
}

func init() { proto.RegisterFile("pb/meetings/meetings.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xd3, 0xa6, 0x4d, 0x26, 0x4d, 0x11, 0x8b, 0x55, 0x19, 0x17, 0x44, 0x64, 0xa4, 0x2a,
	0x07, 0x64, 0xab, 0x41, 0x9c, 0x40, 0x08, 0xf1, 0x7b, 0xa1, 0x12, 0x32, 0xe5, 0x92, 0x8b, 0xd9,
	0xc4, 0x93, 0x68, 0x15, 0x67, 0xd7, 0xd8, 0x1b, 0x04, 0x39, 0x70, 0x40, 0xe2, 0x01, 0x10, 0x2f,
	0xc0, 0x3b, 0xf1, 0x0a, 0xdc, 0x79, 0x05, 0xb4, 0xb6, 0x37, 0xe4, 0xd7, 0x32, 0x37, 0xef, 0xcc,
	0x37, 0xf3, 0xcd, 0x37, 0xfb, 0xad, 0xc1, 0x8e, 0x07, 0xde, 0x14, 0x51, 0x32, 0x3e, 0x4e, 0x17,
	0x1f, 0x6e, 0x9c, 0x08, 0x29, 0xc8, 0xcd, 0x81, 0x10, 0x13, 0xc6, 0xc7, 0xc1, 0x90, 0x46, 0xc8,
	0x43, 0x9a, 0xb8, 0x1a, 0x60, 0x9f, 0x8d, 0x85, 0x18, 0x47, 0xe8, 0x65, 0xc0, 0xc1, 0x6c, 0xe4,
	0xe1, 0x34, 0x96, 0x9f, 0xf3, 0x3a, 0xbb, 0xb3, 0x9e, 0x1c, 0x31, 0x8c, 0xc2, 0x60, 0x4a, 0xd3,
	0x49, 0x81, 0xb8, 0x55, 0x20, 0x68, 0xcc, 0x3c, 0xca, 0xb9, 0x90, 0x54, 0x32, 0xc1, 0x0b, 0x5e,
	0xe7, 0x09, 0x1c, 0x5c, 0xb1, 0x29, 0x92, 0x33, 0x68, 0x86, 0x54, 0x62, 0x20, 0xd9, 0x14, 0x2d,
	0xa3, 0x63, 0x74, 0x9b, 0x7e, 0x43, 0x05, 0x74, 0x52, 0xc5, 0x83, 0xb9, 0xe0, 0x68, 0xd5, 0xf2,
	0xa4, 0x0a, 0xf4, 0x05, 0x47, 0xe7, 0x8f, 0x01, 0x47, 0x97, 0xf9, 0xac, 0xe4, 0x14, 0x0e, 0x63,
	0x9a, 0x20, 0x97, 0x45, 0x8b, 0xe2, 0x44, 0x4e, 0xa0, 0xc6, 0xc2, 0xa2, 0xb2, 0xc6, 0x42, 0xf2,
	0x00, 0xea, 0xa9, 0xa4, 0x89, 0xb4, 0xf6, 0x3b, 0x46, 0xb7, 0xd5, 0xbb, 0xe3, 0xee, 0x54, 0xef,
	0xaa, 0x01, 0xfc, 0x1c, 0x4d, 0x2e, 0x60, 0x1f, 0x79, 0x68, 0x1d, 0x54, 0x2b, 0x52, 0x58, 0x62,
	0x42, 0x5d, 0x32, 0x19, 0xa1, 0x55, 0xcf, 0xc8, 0xf3, 0x03, 0xe9, 0x40, 0x2b, 0xc4, 0x74, 0x98,
	0xb0, 0x58, 0xed, 0xc2, 0x3a, 0xcc, 0x72, 0xcb, 0x21, 0x62, 0x43, 0x23, 0x12, 0xc3, 0x6c, 0x55,
	0xd6, 0x51, 0xae, 0x58, 0x9f, 0x9d, 0xbb, 0x70, 0xfd, 0x15, 0xca, 0x42, 0xb3, 0x8f, 0x1f, 0x66,
	0x98, 0x6a, 0x89, 0x86, 0x96, 0xe8, 0x30, 0xb8, 0xf1, 0x9a, 0xa5, 0x1a, 0x95, 0x6a, 0xd8, 0xae,
	0x0d, 0x9d, 0x41, 0x33, 0xa6, 0x63, 0x0c, 0x52, 0x36, 0xcf, 0x57, 0x5c, 0xf7, 0x1b, 0x2a, 0xf0,
	0x96, 0xcd, 0x91, 0xdc, 0x06, 0xc8, 0x92, 0x52, 0x4c, 0x90, 0x67, 0x3b, 0x6b, 0xfa, 0x19, 0xfc,
	0x4a, 0x05, 0x9c, 0x2f, 0x60, 0xae, 0x52, 0xa5, 0xb1, 0xe0, 0x29, 0x92, 0xc7, 0xd0, 0xd0, 0x1b,
	0xb1, 0x8c, 0xce, 0x7e, 0xb7, 0xd5, 0x73, 0x4a, 0x76, 0xa6, 0xf5, 0x2c, 0x6a, 0xc8, 0x39, 0x5c,
	0xe3, 0xf8, 0x49, 0x06, 0x4b, 0xdc, 0xf9, 0x15, 0xb6, 0x55, 0xf8, 0xcd, 0x82, 0x3f, 0x02, 0xf3,
	0x59, 0x82, 0x54, 0xe2, 0xda, 0x4a, 0x76, 0x69, 0x7d, 0x04, 0x47, 0x05, 0x47, 0xd6, 0xaf, 0xda,
	0x58, 0xba, 0xc4, 0xf9, 0x6e, 0x80, 0xf9, 0x2e, 0x0e, 0x37, 0xe9, 0x96, 0xda, 0x1a, 0xff, 0xdd,
	0x96, 0x3c, 0x84, 0xd6, 0x2c, 0xeb, 0x9a, 0xbd, 0x9d, 0x62, 0x30, 0xdb, 0xcd, 0x1f, 0x8f, 0xab,
	0x9f, 0x97, 0xfb, 0x52, 0x3d, 0xaf, 0x4b, 0x9a, 0x4e, 0x7c, 0xc8, 0xe1, 0xea, 0xdb, 0x39, 0x07,
	0xf3, 0x39, 0x46, 0xb8, 0x31, 0xd2, 0x9a, 0x29, 0x7a, 0x3f, 0x0f, 0xa0, 0xa1, 0xaf, 0x89, 0xbc,
	0x07, 0xf8, 0x67, 0x23, 0x72, 0xaf, 0x64, 0xd8, 0x0d, 0xb7, 0xd9, 0x15, 0xa4, 0x39, 0x7b, 0xe4,
	0x9b, 0x01, 0xc7, 0xcb, 0xce, 0x20, 0x6e, 0x49, 0xd9, 0x16, 0xb7, 0xda, 0x5e, 0x65, 0x7c, 0x6e,
	0x39, 0xc7, 0xfc, 0xfa, 0xeb, 0xf7, 0x8f, 0xda, 0x09, 0x39, 0xf6, 0x3e, 0x5e, 0x2c, 0x7e, 0x71,
	0x64, 0x04, 0xed, 0x15, 0x83, 0x90, 0xb2, 0xbe, 0xdb, 0xac, 0x54, 0x51, 0xef, 0x08, 0xda, 0x2b,
	0xce, 0x28, 0xe5, 0xd9, 0xe6, 0xa1, 0x8a, 0x3c, 0x7d, 0x68, 0xaf, 0x5c, 0x77, 0x29, 0xcf, 0x36,
	0x63, 0xd8, 0xa7, 0x1b, 0xc6, 0x7a, 0xa1, 0x7e, 0xea, 0xce, 0xde, 0x53, 0xe8, 0x2f, 0x1e, 0xe0,
	0xe0, 0x30, 0xcb, 0xde, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x21, 0xa7, 0x57, 0x39, 0x06,
	0x00, 0x00,
}
